sonar.organization=narodriguezb
sonar.projectKey=narodriguezb_rag-backend
sonar.sources=backend
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=backend/chroma_db/**,mutants/**,.venv/**,scripts/**
